Feat 3.1 design improvement
fortinet/autoscale-core pull request #3
Opened 2020-09-08 22:24 UTC by JaydenLiang

2020-09-09 05:00 UTC, klc178 requested changes

2020-09-09 16:50 UTC, JaydenLiang commented on autoscale-core.ts
> +                'master-ip': updatedPrimaryIp
this change needs to be supported on FOS side first. skip it for now.

2020-09-09 17:03 UTC, JaydenLiang commented on fortigate-autoscale/assets/configset/baseconfig
> +    set role master
This change on FOS CLI config needs to be supported on FOS side first. skip it for now.

2020-09-09 17:06 UTC, JaydenLiang commented on autoscale-setting.ts
> +    PaygScalingGroupDesiredCapacity = 'scaling-group-desired-capacity',
Terms in our code are generic terms that do not tie to any specific platform. We still use the abbr. PAYG and BYOL to refer the two pricing models.

2020-09-09 17:07 UTC, JaydenLiang commented on autoscale-setting.ts
> +    [AutoscaleSetting.PaygScalingGroupDesiredCapacity]: {
Terms in our code are generic terms that do not tie to any specific platform. We still use the abbr. PAYG and BYOL to refer the two pricing models.

2020-09-09 17:08 UTC, JaydenLiang commented on fortigate-autoscale/aws/aws-fortigate-autoscale-service.ts
> +        const paygGroupName = settings.get(AwsFortiGateAutoscaleSetting.PaygScalingGroupName).value;
Terms in our code are generic terms that do not tie to any specific platform. We still use the abbr. PAYG and BYOL to refer the two pricing models.

2020-09-09 17:08 UTC, JaydenLiang commented on fortigate-autoscale/aws/aws-fortigate-autoscale-service.ts
> +        if (paygGroupName) {
Terms in our code are generic terms that do not tie to any specific platform. We still use the abbr. PAYG and BYOL to refer to the two pricing models.

2020-09-09 18:18 UTC, klc178 commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +            'groups of services protected by FortiGate.',
```suggestion
            'The DNS name of the internal elastic load balancer ' +
            'used by the FortiGate Autoscale solution.',
```

2020-09-10 01:03 UTC, JaydenLiang commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +            'FortiGate to the protected services behind the load balancer.',
```suggestion
            'FortiGates to the protected services behind the load balancer.',
```

2020-09-10 01:03 UTC, JaydenLiang commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +            'FortiGate to the protected services behind the load balancer.',
```suggestion
            'FortiGates to the protected services behind the load balancer.',
```

2020-09-10 01:08 UTC, JaydenLiang commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +            'FortiGate to the protected services behind the load balancer.',
```suggestion
            'FortiGates to the protected services behind the load balancer.',
```

2020-09-10 23:38 UTC, klc178 commented on fortigate-autoscale/aws/aws-routing-egress-traffic-via-primary-vm-strategy.ts
> +                        ' This is a fatal error and an impposible situation!'
how is this outdated?

2020-09-10 23:44 UTC, klc178 commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +        description: 'Virtual Network ID of the FortiGate Autoscale.',
This has not been applied yet.

2020-09-10 23:44 UTC, klc178 commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +        description: 'Virtual Network CIDR of the FortiGate Autoscale.',
This has not been applied yet.

2020-09-10 23:46 UTC, klc178 commented on fortigate-autoscale/fortigate-autoscale-settings.ts
> +            'groups of services protected by FortiGate.',
This has not been applied yet.

2020-09-10 23:48 UTC, klc178 commented
Changes suggested in fortigate-autoscale/fortigate-autoscale-settings.ts for lines 60, 67, 83-84 ave not been applied yet.

2020-09-10 23:54 UTC, JaydenLiang commented
> Changes suggested in fortigate-autoscale/fortigate-autoscale-settings.ts for lines 60, 67, 83-84 ave not been applied yet.

now they are done in https://github.com/fortinet/autoscale-core/pull/3/commits/e31489352415002a95dfc3e94f5e833c844299d8

2020-09-10 23:57 UTC, klc178 commented on fortigate-autoscale/fortigate-autoscale-settings.ts
>              'The DNS name of the elastic load balancer for the scaling ' +
This line is no longer needed. It seems my previous suggestion only selected one of two lines.

2020-09-11 00:01 UTC, JaydenLiang commented on fortigate-autoscale/fortigate-autoscale-settings.ts
>              'The DNS name of the elastic load balancer for the scaling ' +
```suggestion
```

2020-09-11 00:02 UTC, klc178 approved these changes

2020-09-11 00:13 UTC, jamie-pate approved these changes

2020-09-11 00:17 UTC, merged