feature: reorganizing module reference
fortinet/autoscale-core pull request #37
Opened 2021-03-08 22:52 UTC by JaydenLiang

This feature change reorganizes the file references in core module and sub modules: aws and azure.

1.  ./index now only exports purely core-related file references.
2. ./fortigate-autoscale/index now only exports fortigate-autoscale level implementation references and core references exported in 1.
3. ./fortigate-autoscale/aws/index now only exports fortigate-autoscale-aws implementation references as well as everything in 2.
4. ./fortigate-autoscale/azure/index now only exports fortigate-autoscale-azure implementation references as well as everything in 2.

The above changes solve these problems:
1. when referencing autoscale-core in dependent project, it likely has some side effects caused by unrelated sub modules. For instance, in project [fortigate-autoscale-azure](https://github.com/fortinet/fortigate-autoscale-azure), an unrelated bug in the aws submodule has caused compilation errors. The new approach **reduces the chance of** such side effects.
2. it's hard to split the submodules, especially, soon in the future we might need to migrate the submodule to their own project. In the new approach it will be as easy as cutting and pasting files.
3. it isn't intuitive to import modules from fortigate-autoscale, core into the platform-specific module files. The old approach has to maintain a full list of relative-module resolutions in every module file. Re-organizing module will result in a ton of file update for module resolution changes. In the new approach, only some index.ts requires update on the lines of export * from '<module url>'

2021-03-08 23:28 UTC, jamie-pate requested changes

2021-03-08 23:28 UTC, jamie-pate commented on fortigate-autoscale/aws/index.ts
> +export * from '../index';
You can avoid reaching across like this completely by using 'paths' in tsconfig and 'alias' in webpack.config as discussed.

Treat cross-module dependencies as top-level 'node_modules' even if they are local, by adding path/alias settings in tsconfig/webpack.config.

This decouples the modules and allows them to be moved around later.

2021-03-18 00:33 UTC, jamie-pate approved these changes

2021-03-31 20:53 UTC, JaydenLiang commented
Despite that minor bugs are caught, the feature branch looks good overall. merge it and move on to bug fixing.

2021-03-31 20:54 UTC, merged